// <auto-generated />
using System;
using KarmaWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KarmaWebAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250330184619_AnyEscolar")]
    partial class AnyEscolar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KarmaWebAPI.Models.AnyEscolar", b =>
                {
                    b.Property<int>("id_anyEscolar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_anyEscolar"));

                    b.Property<bool>("actiu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dataFiCurs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataIniciCurs")
                        .HasColumnType("datetime2");

                    b.HasKey("id_anyEscolar");

                    b.ToTable("AnyEscolar");
                });
#pragma warning restore 612, 618
        }
    }
}
