// <auto-generated />
using System;
using KarmaWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KarmaWebAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260516144823_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KarmaWebAPI.Models.Alumne", b =>
                {
                    b.Property<string>("NIA")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Actiu")
                        .HasColumnType("bit");

                    b.Property<string>("Cognoms")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("IdAnyEscolar")
                        .HasColumnType("int");

                    b.Property<long?>("IdClasse")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdGrup")
                        .HasColumnType("bigint");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NIA");

                    b.HasIndex("IdGrup");

                    b.HasIndex("IdAnyEscolar", "IdClasse");

                    b.ToTable("Alumnes");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.AnyEscolar", b =>
                {
                    b.Property<int>("IdAnyEscolar")
                        .HasColumnType("int");

                    b.Property<bool>("Actiu")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("DataFiCurs")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataIniciCurs")
                        .HasColumnType("date");

                    b.Property<bool>("ReiniciaCadaAvaluacio")
                        .HasColumnType("bit");

                    b.Property<double>("SaldoKarmaInicial")
                        .HasColumnType("float");

                    b.HasKey("IdAnyEscolar");

                    b.ToTable("AnyEscolars");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.ApiUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KarmaWebAPI.Models.Avaluacio", b =>
                {
                    b.Property<long>("IdAvaluacio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdAvaluacio"));

                    b.Property<DateOnly>("DataFinal")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicial")
                        .HasColumnType("date");

                    b.Property<int>("IdAnyEscolar")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NotaMaximaKarma")
                        .HasColumnType("float");

                    b.Property<double>("NotaMinimaKarma")
                        .HasColumnType("float");

                    b.HasKey("IdAvaluacio");

                    b.HasIndex("IdAnyEscolar");

                    b.ToTable("Avaluacions");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.Categoria", b =>
                {
                    b.Property<long>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCategoria"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Comentaris")
                        .HasMaxLength(999)
                        .HasColumnType("nvarchar(999)");

                    b.Property<string>("Descripcio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Editable")
                        .HasColumnType("bit");

                    b.Property<long>("IdTipusCategoria")
                        .HasColumnType("bigint");

                    b.Property<double>("NumPunts")
                        .HasColumnType("float");

                    b.HasKey("IdCategoria");

                    b.HasIndex("IdTipusCategoria");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.Classe", b =>
                {
                    b.Property<int>("IdAnyEscolar")
                        .HasColumnType("int");

                    b.Property<long>("IdClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdClasse"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdAnyEscolar", "IdClasse");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.ConfiguracioKarma", b =>
                {
                    b.Property<long>("IdConfiguracioKarma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdConfiguracioKarma"));

                    b.Property<string>("ColorKarma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAnyEscolar")
                        .HasColumnType("int");

                    b.Property<int>("NivellPrivilegis")
                        .HasColumnType("int");

                    b.Property<double>("NumPuntsMaxim")
                        .HasColumnType("float");

                    b.Property<double>("NumPuntsMinim")
                        .HasColumnType("float");

                    b.HasKey("IdConfiguracioKarma");

                    b.HasIndex("IdAnyEscolar");

                    b.ToTable("ConfiguracionsKarma");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.Grup", b =>
                {
                    b.Property<long>("IdGrup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdGrup"));

                    b.Property<DateTime?>("DataUltimaActualitzacioKarma")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAnyEscolar")
                        .HasColumnType("int");

                    b.Property<long>("IdClasse")
                        .HasColumnType("bigint");

                    b.Property<string>("KarmaBase")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdGrup");

                    b.HasIndex("IdAnyEscolar", "IdClasse");

                    b.ToTable("Grups");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.KarmaAlumne", b =>
                {
                    b.Property<long>("IdKarmaAlumne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdKarmaAlumne"));

                    b.Property<string>("Comentaris")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdAvaluacio")
                        .HasColumnType("bigint");

                    b.Property<string>("KarmaActual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KarmaInicial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIA")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<double?>("NotaKarma")
                        .HasColumnType("float");

                    b.Property<double>("NumPuntsActuals")
                        .HasColumnType("float");

                    b.Property<double?>("NumPuntsAvaluacioAnteriorDrv")
                        .HasColumnType("float");

                    b.Property<double>("NumPuntsInicials")
                        .HasColumnType("float");

                    b.HasKey("IdKarmaAlumne");

                    b.HasIndex("IdAvaluacio");

                    b.HasIndex("NIA", "IdAvaluacio");

                    b.ToTable("KarmaAlumnes");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.Materia", b =>
                {
                    b.Property<long>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdMateria"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMateria");

                    b.ToTable("Materies");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.Privilegi", b =>
                {
                    b.Property<long>("IdPrivilegi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPrivilegi"));

                    b.Property<bool>("Actiu")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAnyEscolar")
                        .HasColumnType("int");

                    b.Property<int>("NivellPrivilegi")
                        .HasColumnType("int");

                    b.Property<string>("Tipus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPrivilegi");

                    b.HasIndex("IdAnyEscolar");

                    b.ToTable("Privilegis");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.PrivilegiAssignat", b =>
                {
                    b.Property<long>("IdPrivilegiAssignat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPrivilegiAssignat"));

                    b.Property<string>("AlumneNIA")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CodiIntern")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataCreacio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExecucio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdPrivilegi")
                        .HasColumnType("bigint");

                    b.Property<string>("NIA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NivellPrivilegi")
                        .HasColumnType("int");

                    b.Property<long>("PrivilegiIdPrivilegi")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPrivilegiAssignat");

                    b.HasIndex("AlumneNIA");

                    b.HasIndex("PrivilegiIdPrivilegi");

                    b.ToTable("PrivilegisAssignats");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.Professor", b =>
                {
                    b.Property<string>("IdProfessor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Actiu")
                        .HasColumnType("bit");

                    b.Property<string>("Cognoms")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("PertanyAEquipDirectiu")
                        .HasColumnType("bit");

                    b.HasKey("IdProfessor");

                    b.ToTable("Professors");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.Puntuacio", b =>
                {
                    b.Property<long>("IdPuntuacio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPuntuacio"));

                    b.Property<string>("AlumneNIA")
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("AvaluacioIdAvaluacio")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoriaIdCategoria")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCreacio")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DataEvent")
                        .HasColumnType("date");

                    b.Property<string>("DescripcioAdicional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdAvaluacio")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCategoria")
                        .HasColumnType("bigint");

                    b.Property<long>("IdClasse")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdGrup")
                        .HasColumnType("bigint");

                    b.Property<string>("IdProfessor")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Motiu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIA")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomClasse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomGrup")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("NumPunts")
                        .HasColumnType("float");

                    b.Property<string>("Tipus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("IdPuntuacio");

                    b.HasIndex("AlumneNIA");

                    b.HasIndex("AvaluacioIdAvaluacio");

                    b.HasIndex("CategoriaIdCategoria");

                    b.HasIndex("IdProfessor");

                    b.HasIndex("NIA", "IdAvaluacio");

                    b.ToTable("Puntuacions");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.TipusCategoria", b =>
                {
                    b.Property<long>("IdTipusCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdTipusCategoria"));

                    b.Property<bool>("Actiu")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipusCategoria");

                    b.ToTable("TipusCategories");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProfessorDeClasse", b =>
                {
                    b.Property<long>("IdProfessorDeClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdProfessorDeClasse"));

                    b.Property<int>("IdAnyEscolar")
                        .HasColumnType("int");

                    b.Property<long>("IdClasse")
                        .HasColumnType("bigint");

                    b.Property<long>("IdMateria")
                        .HasColumnType("bigint");

                    b.Property<string>("IdProfessor")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdProfessorDeClasse");

                    b.HasIndex("IdMateria");

                    b.HasIndex("IdAnyEscolar", "IdClasse");

                    b.HasIndex("IdProfessor", "IdClasse", "IdMateria")
                        .IsUnique();

                    b.ToTable("ProfessorsDeClasse");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.Alumne", b =>
                {
                    b.HasOne("KarmaWebAPI.Models.Grup", "Grup")
                        .WithMany()
                        .HasForeignKey("IdGrup");

                    b.HasOne("KarmaWebAPI.Models.Classe", "Classe")
                        .WithMany("Alumnes")
                        .HasForeignKey("IdAnyEscolar", "IdClasse")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Classe");

                    b.Navigation("Grup");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.Avaluacio", b =>
                {
                    b.HasOne("KarmaWebAPI.Models.AnyEscolar", "AnyEscolar")
                        .WithMany()
                        .HasForeignKey("IdAnyEscolar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnyEscolar");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.Categoria", b =>
                {
                    b.HasOne("KarmaWebAPI.Models.TipusCategoria", "TipusCategoria")
                        .WithMany("Categories")
                        .HasForeignKey("IdTipusCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipusCategoria");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.Classe", b =>
                {
                    b.HasOne("KarmaWebAPI.Models.AnyEscolar", "AnyEscolar")
                        .WithMany()
                        .HasForeignKey("IdAnyEscolar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnyEscolar");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.ConfiguracioKarma", b =>
                {
                    b.HasOne("KarmaWebAPI.Models.AnyEscolar", "AnyEscolar")
                        .WithMany()
                        .HasForeignKey("IdAnyEscolar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnyEscolar");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.Grup", b =>
                {
                    b.HasOne("KarmaWebAPI.Models.Classe", "Classe")
                        .WithMany("Grups")
                        .HasForeignKey("IdAnyEscolar", "IdClasse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.KarmaAlumne", b =>
                {
                    b.HasOne("KarmaWebAPI.Models.Avaluacio", "Avaluacio")
                        .WithMany()
                        .HasForeignKey("IdAvaluacio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KarmaWebAPI.Models.Alumne", "Alumne")
                        .WithMany()
                        .HasForeignKey("NIA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumne");

                    b.Navigation("Avaluacio");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.Privilegi", b =>
                {
                    b.HasOne("KarmaWebAPI.Models.AnyEscolar", "AnyEscolar")
                        .WithMany("Privilegis")
                        .HasForeignKey("IdAnyEscolar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnyEscolar");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.PrivilegiAssignat", b =>
                {
                    b.HasOne("KarmaWebAPI.Models.Alumne", "Alumne")
                        .WithMany()
                        .HasForeignKey("AlumneNIA");

                    b.HasOne("KarmaWebAPI.Models.Privilegi", "Privilegi")
                        .WithMany()
                        .HasForeignKey("PrivilegiIdPrivilegi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumne");

                    b.Navigation("Privilegi");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.Puntuacio", b =>
                {
                    b.HasOne("KarmaWebAPI.Models.Alumne", "Alumne")
                        .WithMany()
                        .HasForeignKey("AlumneNIA");

                    b.HasOne("KarmaWebAPI.Models.Avaluacio", "Avaluacio")
                        .WithMany()
                        .HasForeignKey("AvaluacioIdAvaluacio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KarmaWebAPI.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaIdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KarmaWebAPI.Models.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("IdProfessor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumne");

                    b.Navigation("Avaluacio");

                    b.Navigation("Categoria");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KarmaWebAPI.Models.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KarmaWebAPI.Models.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KarmaWebAPI.Models.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KarmaWebAPI.Models.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProfessorDeClasse", b =>
                {
                    b.HasOne("KarmaWebAPI.Models.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KarmaWebAPI.Models.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("IdProfessor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KarmaWebAPI.Models.Classe", "Classe")
                        .WithMany("ProfessorsDeClasse")
                        .HasForeignKey("IdAnyEscolar", "IdClasse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Materia");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.AnyEscolar", b =>
                {
                    b.Navigation("Privilegis");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.Classe", b =>
                {
                    b.Navigation("Alumnes");

                    b.Navigation("Grups");

                    b.Navigation("ProfessorsDeClasse");
                });

            modelBuilder.Entity("KarmaWebAPI.Models.TipusCategoria", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
